driver:
  name: terraform
  root_module_directory: test/fixtures
  variable_files:
    - test/fixtures/test.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: az-basic-infra

suites:
  - name: default
    verifier:
      color: true
      systems: 
        - name: local
          backend: local
          controls:
            - outputs
        - name: azure
          backend: azure
          controls:
            - azureVnet
            - azureSubnets