driver:
  name: terraform
  root_module_directory: test/fixtures
  variable_files:
    - test/fixtures/test.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform

  systems:
  
    - name: local
      backend: local

platforms:
  - name: az-basic-infra

suites:
  - name: default